### ISSUE TITLE
STFT.inverse()  could not work correct under batch operations

### ISSUE THREAD

**Issue by mcw519** [KinWaiCheuk/nnAudio#100]
Hi,

I tried the STFT and its inverse function found that could only be worked correct under batch size is 1.  
Looks like more than 1 batch size, the batch audio would be merged together.  
Is any idea for this issue?

Thanks.

**Comment by mcw519** [comment]
Simple code to reproduce it.

![image](https://user-images.githubusercontent.com/50145303/128465642-4755c668-4542-4d0f-9c80-857d9312f03b.png)

**Comment by mcw519** [comment]
Hi,

I found that the error happen inside the `extend_fbins()`  
I changed this line:
`X_upper = torch.flip(X[:,1:-1],(0,1))`
to
`X_upper = X[:,1:-1].flip(1)`
and it worked!

![image](https://user-images.githubusercontent.com/50145303/128491654-dd225f2d-afbc-4106-ad8e-fbb7482c00b0.png)

**Comment by KinWaiCheuk** [comment]
> Hi,
> 
> I found that the error happen inside the `extend_fbins()`
> I changed this line:
> `X_upper = torch.flip(X[:,1:-1],(0,1))`
> to
> `X_upper = X[:,1:-1].flip(1)`
> and it worked!
> 
> ![image](https://user-images.githubusercontent.com/50145303/128491654-dd225f2d-afbc-4106-ad8e-fbb7482c00b0.png)

Oh! Good job finding and fixing the problem. I am also trying to figure out what's wrong just now, haha.
Do you mind making a pull request?

**Comment by mcw519** [comment]
sure. ^^
