### ISSUE TITLE
CQT

### ISSUE THREAD

**Issue by benihime91** [KinWaiCheuk/nnAudio#104]
Hi, Does CQT automatically apply `band_pass` filtering based on `fmin`,  `fmax`, `sr` given ?

**Comment by KinWaiCheuk** [comment]
Hi @benihime91, I didn't exactly use a `band_pass` filtering to filter out frequencies that are lower than `fmin` or higher than `fmax`.

Instead, the CQT kernels are created according to `fmin`, `fmax`, and `sr` given, so that the lowest bin starts at `fmin` and the highest bin ends at `fmax`.

**Comment by benihime91** [comment]
Yep that makes sense. Thanks for the reply
