### ISSUE TITLE
[Feature request] Log2 (octave) normalization in STFT

### ISSUE THREAD

**Issue by Manza12** [KinWaiCheuk/nnAudio#111]
Currently when we use the parameter 'log' for STFT frequency scale it spaces logarithmically the frequencies with base e. I think it will be nice to have also logarithmic spacing with base 2, such that it will be more music related. 
It may be just a new freq_scale option, like 'log2'. If you want I can do a PR :)

**Comment by KinWaiCheuk** [comment]
Yes, a log2 scale would be useful in some cases! Sure, please go ahead!
