### ISSUE TITLE
Difficulty in using VQT feature with GPU support

### ISSUE THREAD

**Issue by cheriell** [KinWaiCheuk/nnAudio#117]
Hi Kin Wai,

Thank you so much for releasing such a helpful package!

I have some difficulties using the new VQT feature with GPU support. The code and error message is as follows:

![Screenshot 2022-10-09 at 10 06 27](https://user-images.githubusercontent.com/32418246/194748051-29fe5338-94e1-4709-ac01-4c4d83f686b4.png)
![Screenshot 2022-10-09 at 10 07 12](https://user-images.githubusercontent.com/32418246/194748096-82f90769-45a0-4251-84da-1efa476c72d1.png)

The same issue doesn't happen if I change the VQT to CQT.

Could you help me with it?

Many thanks!

**Comment by KinWaiCheuk** [comment]
Solved with commit [dc222b4](https://github.com/KinWaiCheuk/nnAudio/commit/dc222b438ecac32492354a2df0b4faa24f473cc2)
