### ISSUE TITLE
Looking for a simple example of STFT/ iSTFT

### ISSUE THREAD

**Issue by robertmckean** [KinWaiCheuk/nnAudio#125]
I'm looking for a very simple example. I want to 1) read a wav file, 2) convert to STFT Spectrogram, then convert back to a wav file using iSTFT. I'm using PyTorch. I cannot get iSTFT to work with a real wav file. This works with nnAudio for iSTFT:

    y = torch.randn(1, 2048, 128, 2)
    spec_layer = Spectrogram.iSTFT()(y)
    print("spec_layer.shape: ", spec_layer.shape) # -->  spec_layer.shape:  torch.Size([1, 65024])

   
But does the file STFT file need to have the shape of (1, 2048, 128, 2)? It seems complex to tweak the parameters of of the STFT in order to get a perfectly matching post-STFT output shape. I can't make iSTFT work with a real wav file. I get errors similar to: "RuntimeError: Calculated padded input size per channel: (1025 x 87). Kernel size: (2048 x 1). Kernel size can't be greater than actual input size"

With librosa, it's so simple:

    x, sr = librosa.load("original_slice.wav")
    # Compute the STFT spectrogram
    stft = librosa.stft(x, n_fft=2048, hop_length=512, win_length=2048, window='hann')
    stft_db = librosa.amplitude_to_db(abs(stft))
    # Compute the inverse STFT spectrogram
    x_istft = librosa.istft(stft, hop_length=512, win_length=2048, window='hann')

Is there a simple way to do this transformation in nnAudio? Am I missing something really obvious?

Any help would be hugely appreciated.

Thanks!
::Robert

**Comment by robertmckean** [comment]
Here is sample code that I am using. I chose the random tensor size because that is the shape of the output of the STFT process:

from nnAudio import Spectrogram
import torch

# Load the STFT spectrogram
stft_spectrogram = torch.randn(1, 1025, 45133, 2) # example data

# Create an iSTFT module
istft = Spectrogram.iSTFT(n_fft=2048, hop_length=256, win_length=1024, window='hann')

# Convert the STFT spectrogram to a waveform
waveform = istft(stft_spectrogram)

I get this error:
RuntimeError: Calculated padded input size per channel: (1025 x 45133). Kernel size: (2048 x 1). Kernel size can't be greater than actual input size

**Comment by robertmckean** [comment]
Alright! Got it to work. The purpose was to go from 'audio --> stft --> istft.forward --> audio'. The trick was to use the iSTFT.forward method and set 'onesided=True'. Phew. Here's the code:

        from nnAudio import Spectrogram
        import torch
        import soundfile as sf
        
        # Load the audio file
        x, sr = sf.read(r"D:\Python\common\Guitar\slice_librosa.wav")
        print("x.shape: ", x.shape)
        
        # Convert the audio data to a PyTorch Tensor
        x = torch.tensor(x).float().cuda()
        print("x.shape (tensor): ", x.shape)
        
        # Create an STFT spectrogram using nnAudio
        stft = Spectrogram.STFT(n_fft=2048, hop_length=512, win_length=2048, window='hann').cuda()
        
        # Compute the STFT spectrogram
        stft_spectrogram = stft(x.unsqueeze(0)).cuda()
        print("stft_spectrogram.shape: ", stft_spectrogram.shape)
        
        # Create an iSTFT instance
        istft = Spectrogram.iSTFT(n_fft=2048, hop_length=512, win_length=2048, window='hann').cuda()
        
        # Convert the STFT spectrogram to a waveform
        waveform = istft.forward(stft_spectrogram, onesided=True, length=x.shape[-1]).cuda()
        print("waveform.shape: ", waveform.shape)
        
        torch.cuda.empty_cache()
        
        # Convert the tensor to a numpy array
        waveform_np = waveform.squeeze().cpu().numpy()
        print("waveform_np.shape: ", waveform_np.shape)
        
        # Save the array as a WAV file
        sf.write(r"D:\Python\common\Guitar\guitar_istft.wav", waveform_np, samplerate=44100)

This is the output:
        x.shape:  (220500,)
        x.shape (tensor):  torch.Size([220500])
        STFT kernels created, time used = 0.0676 seconds
        stft_spectrogram.shape:  torch.Size([1, 1025, 431, 2])
        iSTFT kernels created, time used = 0.1092 seconds
        waveform.shape:  torch.Size([1, 220500])
        waveform_np.shape:  (220500,)

If anyone has any suggestions to make it cleaner or faster, please let me know!

**Comment by migperfer** [comment]
Thanks for noticing this! Looks like STFT is returning a `onesided` version of the signal, yet the default value of the iSTFT is not the `onesided`one!

Your code looks good to me, not sure it could be made faster :)
