### ISSUE TITLE
A compare table with detail might be helpful

### ISSUE THREAD

**Issue by HudsonHuang** [KinWaiCheuk/nnAudio#23]
First of all, thanks for your nice job! It works on my program perfectly.

But as there're already so many spectual processing Libs, a compare table in detail might make your work more outstanding.

I made a quick and dirty version for this:

| Feature | [nnAudio](https://github.com/KinWaiCheuk/nnAudio) | [torch.stft](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/SpectralOps.cpp) | [kapre](https://github.com/keunwoochoi/kapre) | [torchaudio](https://github.com/pytorch/audio) | [tf.signal](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/ops/signal)(or else tf. stuff) | [torch-stft](https://github.com/pseeth/torch-stft) | [librosa](https://github.com/librosa/librosa) |
| ------- | ------- | ---------- | ----- | ---------- | ---------------------------- | ---------- | ------- |
| Trainable | 1  | 0 | 1 | 0 | 0 | 1 | 0 |
| ModelConvert* | 1  | 0 | 1 | 0 | 0 | 1 | 0 |
| Speed(Need test**) | 0  | 0 | 0 | 0 | 0 | 0 | 0 |
| Differentiable(Not sure**) | 1  | 1 | 1 | 1 | 1 | 1 | 0 |
| Mel | 1  | 0 | 1 | 1 | 1 | 0 | 1 |
| MFCC | 0  | 0 | 0 | 1 | 1 | 0 | 1 |
| CQT | 1  | 0 | 0 | 0 | 0 | 0 | 1 |
| GPU support | 1  | 1 | 1 | 1 | 1 | 1 | 0 |

* *Model Convert: As many mobile neural networks only support limited OPs, to deploy on mobile device, the ability to convert to other framework (eg: ONNX) is important. May also referrance [here.](https://github.com/onnx/tutorials/blob/master/tutorials/PytorchAddExportSupport.md)
* **More check needed.

**Comment by KinWaiCheuk** [comment]
This is a cool idea. I will make a comparison table based on your template in a few days.
Thanks for the suggestion!

**Comment by KinWaiCheuk** [comment]
I have included your table in my readme. Thanks for contributing the table.
After asking around people, it seems it is possible to deploy all the libraries to mobile devices. But some might be difficult than others. (For example the one supports ONNX might be easier). So I still need to study more before I put this information (I don't have experience in ONNX yet).

Anyhow, thanks again for your awesome suggestion

**Comment by faroit** [comment]
@KinWaiCheuk did you actually test for onnx export?

**Comment by KinWaiCheuk** [comment]
@faroit I still haven't had a chance to use ONNX yet. If you are currently using ONNX, I will appreciate if you can tell me it works or not.

**Comment by HudsonHuang** [comment]
> @faroit I still haven't had a chance to use ONNX yet. If you are currently using ONNX, I will appreciate if you can tell me it works or not.

Yes, it works perfectly.
