### ISSUE TITLE
link to paper/citation

### ISSUE THREAD

**Issue by danstowell** [KinWaiCheuk/nnAudio#3]
Hi - if I'm not mistaken, it's not obvious how to go from this repository to read the paper or cite it. I recommend adding info in the readme about that

**Comment by KinWaiCheuk** [comment]
Thanks for the suggestion, I have added links to papers and how to cite. This work was submitted as a late-breaking-demo to ISMIR2019. I am still writing the full paper for it. I will link my repository to the main paper once I finished writing it.
