### ISSUE TITLE
STFT Phase shape (1, ..., ..., 2)

### ISSUE THREAD

**Issue by timlod** [KinWaiCheuk/nnAudio#32]
Hi,
Thanks for the library!
I was wondering why the shape for the phase is (1, ..., ..., 2).
Shouldn't the phase, just like taking the magnitude, reduce the dimensionality?

From the documentation:
``Phase`` will return the phase of the STFT reuslt, shape = ``(num_samples, freq_bins,time_steps, 2)``.

**Comment by KinWaiCheuk** [comment]
Hi timlod, thanks for pointing it out. I made some mistakes when implementing the phase output.
Now I have fixed it in version 0.0.12.

You can install it by first removing the old version of nnAudio with
`pip uninstall nnAudio`
and then install version 0.0.12 with
`pip install nnAudio==0.0.12`
