### ISSUE TITLE
Incorrect example in nextpow2

### ISSUE THREAD

**Issue by mgrachten** [KinWaiCheuk/nnAudio#34]
A minor issue, but it may confuse readers that the example given in the doc string of `nextpow2` is incorrect. `nextpow2(6)` equals 3, not 8.

https://github.com/KinWaiCheuk/nnAudio/blob/fd90722ae36968fc7afe217346de1e22d8be44f4/Installation/nnAudio/Spectrogram.py#L105-L124

**Comment by KinWaiCheuk** [comment]
Thanks for point it out, I have fixed the doc string.
