### ISSUE TITLE
some issues in applying

### ISSUE THREAD

**Issue by bryent111** [KinWaiCheuk/nnAudio#44]
Hi, I meet some issues when applying nnAudio in my code:
1, the pip version(use pip install nnAudio) is different from the github version(download from github), for example, in pip version the output_format of STFT is a parameter in init, while in github version it is a parameter of forward. I don't know if there are other differences.
2, how to istft? in github version, there is a inverse method in STFT, but when I use it, there is a mistake:
  File "/home3/lmh/anaconda3/envs/tasnet/lib/python3.7/site-packages/nnAudio-0.1.1-py3.7.egg/nnAudio/Spectrogram.py", line 572, in inverse
    elif len(X.shape) == 4 and self.output_format == "Complex":
  File "/home3/lmh/anaconda3/envs/tasnet/lib/python3.7/site-packages/torch/nn/modules/module.py", line 576, in __getattr__
    type(self).__name__, name))
AttributeError: 'STFT' object has no attribute 'output_format'
by the way, I set two different stft_layer for stft and istft. and if I use one stft_layer for stft and istft, that will be correct. Must I use one stft_layer for stft and istft? when I use the pip version, there is no inverse method. 
Can you check it please? Thanks a lot.

**Comment by bryent111** [comment]
And when I run stft_layer.inverse on GPU, there will be mistake
  File "/home3/lmh/anaconda3/envs/tasnet/lib/python3.7/site-packages/nnAudio-0.1.1-py3.7.egg/nnAudio/Spectrogram.py", line 607, in __inverse
RuntimeError: legacy constructor for device type: cpu was passed device type: cuda, but device type must be: cpu
lin 607 is:
        if is_window_normalized:
            real /= torch.Tensor(window_mask, device=self.device).unsqueeze(0).unsqueeze(-1)
so torch.Tensor can not be used here? I see torch.tensor is ok in other place

**Comment by KinWaiCheuk** [comment]
Hi bryent111, we are still testing and developing the inverse STFT and Griffin-Lim features, so it is not in the stable release. I have just added a dev release in pypi and you can get it with `pip install nnAudio --pre -U`.

Can you try if the problems still persist in the dev release?

**Comment by bryent111** [comment]
hi, KinWaiCheuk. Thanks a lot for your project, it is very interesting. I want to add nnAudio to my E2E model .
I reinstall the 0.1.2 version, and find the issue still remain.
1, I can only use the one stft layer for stft and istft, if I use two separate stft layer for stft and istft, the latter will have mistake:
AttributeError: 'STFT' object has no attribute 'output_format'
2, If I use one stft layer for stft and istft, if using cpu ,it is ok. If using gpu, there will be a mistake in istft:
RuntimeError: legacy constructor for device type: cpu was passed device type: cuda, but device type must be: cpu

**Comment by KinWaiCheuk** [comment]
Hi Bryent, for point 1, is there any necessarily of using two separate layers one for stft another one for istft? Since the istft uses the same convolution kernel from the stft (or else the reconstruction would be wrong if the kernels of istft is different from that of stft). Therefore, we decided to merge the inverse function inside the stft class. And in the next release, we are planing to remove the istft class layer. However, if there is any special circumstances that we need individual layers for each of the stft and istf, maybe we will keep it and fix the error. 

For point 2, we have made a stupid mistake. `torch.tensor` should be use at that line instead of `torch.Tensor`. I am going to make a new pypi release soon, but maybe I will wait for you reply to point 1 to see if we should keep or remove that istft layer.

**Comment by bryent111** [comment]
Hi, KinWaiCheuk. For point 1, in E2E T-F domain speech enhancement and separation, there is a requirement for separate stft and istft. Please refer to this paper "DCCRN Deep Complex Convolution Recurrent Network for Phase-Aware Speech Enhancement" in INTERSPEEC2020, which just use two separate stft and istft layer. In fact, this is equivalent to initializing two modules and learning them separately. Of course, we can use ONE STFT layer for transform and inverse when training, but we can get better flexibility in deep learning with two separate layers, and maybe better performance.

**Comment by KinWaiCheuk** [comment]
I have uploaded a new version 0.1.2.dev2, and it should solve all the existing issues and support a separated iSTFT layer class.

Please do `pip install nnAudio --pre -U` again to get this version.

**Comment by bryent111** [comment]
Thanks a lot, I'll try it.
