### ISSUE TITLE
No module named librosa_filters

### ISSUE THREAD

**Issue by 18445864529** [KinWaiCheuk/nnAudio#51]
I followed Readme and when I tried to from nnAudio import Spectrogram, it threw error as No module named librosa_filters. My librosa version is 0.7.0 just as mentioned in Readme. 
I tried to change the source code from 'librosa_filters' to 'librosa.filters', it was able to import, but when doing the STFT it again threw 'pad_center' is not defined error, so I reckon that would be a function in librosa_filters? Where can I get this librosa_filters module?

**Comment by KinWaiCheuk** [comment]
May I know which version of nnAudio you are using?

**Comment by 18445864529** [comment]
> May I know which version of nnAudio you are using?

0.1.3

**Comment by KinWaiCheuk** [comment]
Can you try `pip install nnAudio==0.1.5a0`? 0.1.3 is known to be broken and has been yanked.

**Comment by 18445864529** [comment]
> Can you try `pip install nnAudio==0.1.5a0`? 0.1.3 is known to be broken and has been yanked.

This works! thank you. 
I previously used simply pip install nnAudio and somehow 0.1.3 was installed by default.
