### ISSUE TITLE
Is there a param named filter scale factor in  nnAudio ???

### ISSUE THREAD

**Issue by yeti-yeti** [KinWaiCheuk/nnAudio#54]
There is a param named filter_scale in librosa.cqt.
filter_scale : float > 0
    Filter scale factor. Small values (<1) use shorter windows
    for improved time resolution.
How can i use this param in nnAudio???
Thank you!!!
librosa.cqt(
    y,
    sr=22050,
    hop_length=512,
    fmin=None,
    n_bins=84,
    bins_per_octave=12,
    tuning=0.0,
    filter_scale=1,
    norm=1,
    sparsity=0.01,
    window='hann',
    scale=True,
    pad_mode='reflect',
    res_type=None,
    dtype=None,
)

**Comment by KinWaiCheuk** [comment]
Currently the filter scale factor is not supported in nnAudio. We are also looking for contributors who can implement this.

**Comment by KinWaiCheuk** [comment]
Solved in pull request [#84](https://github.com/KinWaiCheuk/nnAudio/pull/84)
