### ISSUE TITLE
Inverse STFT

### ISSUE THREAD

**Issue by vkothapally** [KinWaiCheuk/nnAudio#63]
Hello, 

Can you please let me know if we can use multiple audio files in a single batch? Also, do you have an option to compute inverse STFT?

**Comment by KinWaiCheuk** [comment]
Hi, you can pack your audio in the shape of `(batch, audio_len)`, where `batch` is the dimension containing all your audio array. For example, if you have 128 audio array of the length 44100, then the input tensor would be of the shape `(128, 44100)`, i.e. processing 128 audio clips into spectrograms at once.

For inverse STFT, yes. There is an iSTFT class that you can use, and the STFT now also contains the `inverse` method. I have just made a commit to optimize things few hours ago, I will upload a new pypi release very soon.

**Comment by vkothapally** [comment]
Thank you so much for the quick response. That is really helpful. Also, are the parameters in the iSTFT class also trainable similar to STFT?

**Comment by KinWaiCheuk** [comment]
Yes, the `iSTFT` class is also trainable. To have a trainable `STFT` and trainable `iSTFT`, you should define the two classes seperatately. 

The `inverse` method inside `STFT` is sharing the same Fourier kernels as the forward pass. Therefore it is impossible to train the `inverse` if you are only using one single `STFT` class.

**Comment by vkothapally** [comment]
Thank you @KinWaiCheuk. I was going through the code. I have tested it just now and everything seems to been working just great. Thanks a lot for sharing your work.
