### ISSUE TITLE
Installation instructions don't work

### ISSUE THREAD

**Issue by turian** [KinWaiCheuk/nnAudio#80]
I am trying to install master so I can try the Gammatonegram. (Will you make a new pre-release soon?)

I follow the installation instructions here: https://kinwaicheuk.github.io/nnAudio/intro.html#installation

However, it doesn't work. You can see a minimal colab here:

https://colab.research.google.com/drive/15ItkuaZV0XCR7nzsC0mr_3jj374s-Knz?usp=sharing

```
!git clone https://github.com/KinWaiCheuk/nnAudio.git
!cd nnAudio/Installation/ && python3 setup.py install
from nnAudio import Spectrogram
>>> ImportError: cannot import name 'Spectrogram'
```

**Comment by KinWaiCheuk** [comment]
It seems to be a specific problem in Colab, since it is working fine in a local machine.

Can you try this command to install nnAudio in colab instead?
`!pip install git+https://github.com/KinWaiCheuk/nnAudio.git#subdirectory=Installation`

**Comment by turian** [comment]
That appears to work.
