### ISSUE TITLE
Trainable kernels CQT2010v2

### ISSUE THREAD

**Issue by migperfer** [KinWaiCheuk/nnAudio#82]
Hi! First of all thanks for this amazing tool, it's saving me a lot of time!
When I try to make the CQT2010v2 trainable I have the following error 
```
Exception has occurred: NameError
name 'trainable_kernels' is not defined
```
The *trainable_kernels* variable is referred [here](https://github.com/KinWaiCheuk/nnAudio/blob/b14ec264ca9e65e9a225c0b8caaf41a0373961fe/Installation/nnAudio/Spectrogram.py#L1567) but not defined previously. In the documentation is stated that this can be differentiable as well.

The line of code I'm using is `spec.CQT2010v2(sr=sr, n_bins=128, bins_per_octave=16, hop_length=1024, pad_mode='constant', trainable=True)`

**Comment by KinWaiCheuk** [comment]
Hi migperfer, thanks for reporting this bug. I have made a quick fix.
Can you try the latest version via `pip install git+https://github.com/KinWaiCheuk/nnAudio.git#subdirectory=Installation`?

**Comment by migperfer** [comment]
Hi! Sorry for the delay. So far looks like it's working, if I see something weird I'll let you know. Thanks for fixing it so quickly!
