### ISSUE TITLE
missing __version__

### ISSUE THREAD

**Issue by lostanlen** [KinWaiCheuk/nnAudio#83]
Thank you for the great package

It would be good if you could define a global variable `__version__` in the top-level module nnAudio? This way, we could inspect the version of nnAudio we're currently running directly from inside Python.

Thanks!

**Comment by KinWaiCheuk** [comment]
Thanks for the suggestion. Starting from version 0.2.1, it is possible to check the version inside python via `nnAudio.__version__`.

**Comment by lostanlen** [comment]
ok great! many thanks
