### ISSUE TITLE
Example code doesn't work

### ISSUE THREAD

**Issue by aufr33** [KinWaiCheuk/nnAudio#93]
I am trying to run [this example](https://kinwaicheuk.github.io/nnAudio/intro.html#standalone-usage), but I get the error:

> RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same

scipy 1.2.0
numpy 1.14.5
torch 1.7.1+cu110
Python 3.7.4

**Comment by KinWaiCheuk** [comment]
After you have the model, did you do `model.to(device)`?
These nnAudio functions are basically neural networks, so you would also need to move them to the same device as your input.
