### ISSUE TITLE
What about the results of this job in speech tasks? 

### ISSUE THREAD

**Issue by liziru** [KinWaiCheuk/nnAudio#96]
I wonder whether this job works in speech-related tasks, such as speech enhancement, asr. 
Does anyone take a  try in these speech tasks? And what about the results using this job? 
Looking forward to any reply.

**Comment by cirograciapons** [comment]
i used it successfully to train a network for asvspoof challenge. In fact, i compared a regular network inputting features from files ( produced by signal processing c++ library called spro ) against the same network producing them on the fly by a nnAudio Layer ,and both networks got comparable/close results

**Comment by liziru** [comment]
> i used it successfully to train a network for asvspoof challenge. In fact, i compared a regular network inputting features from files ( produced by signal processing c++ library called spro ) against the same network producing them on the fly by a nnAudio Layer ,and both networks got comparable/close results

Got it. Thank you very much.

**Comment by KinWaiCheuk** [comment]
> I wonder whether this job works in speech-related tasks, such as speech enhancement, asr.

Currently I am using the `Melspectrogram()` class for training an ASR model. There should not be any major differences from other major libraries such as `librosa` or `torchaudio`, since the melspectrogram outputs are nearly the same among these libraries (of course, it is still subjected to floating point errors).

So you should be able to use it for other speech-related tasks without problems. If you indeed find any problems or bugs, please feel free to raise an issue :)

**Comment by liziru** [comment]
> > I wonder whether this job works in speech-related tasks, such as speech enhancement, asr.
> 
> Currently I am using the `Melspectrogram()` class for training an ASR model. There should not be any major differences from other major libraries such as `librosa` or `torchaudio`, since the melspectrogram outputs are nearly the same among these libraries (of course, it is still subjected to floating point errors).
> 
> So you should be able to use it for other speech-related tasks without problems. If you indeed find any problems or bugs, please feel free to raise an issue :)

OK, I see. So we are able to achieve a full end-to-end asr system with this job.  Thanks for your great work.

**Comment by KinWaiCheuk** [comment]
If there is no further questions, I will be closing this issue. Feel free to reopen or start a new issue if you have any questions.
