### ISSUE TITLE
Is multi-channel (2/stereo) supported?

### ISSUE THREAD

**Issue by sevagh** [KinWaiCheuk/nnAudio#97]
Hello. Looks like this library is intended to only be used on single channel audio - is this correct?

**Comment by KinWaiCheuk** [comment]
For stereo audio clips, we usually take the average across the channels and convert it back to a mono track.
Or is there any special thing you want to do with a stereo audio clip?

**Comment by sevagh** [comment]
No, that's OK. I was able to add a small "Monoizer(nn.Module)" to take the mean across channels like you said.

I was just uncertain if this was a known library limitation. Thanks.
